# Generated by Django 5.2.7 on 2025-10-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Собран', 'Собран'), ('Собираем', 'Собираем'), ('Курьер в пути', 'Курьер в пути'), ('Доставлен', 'Достален')], max_length=100, verbose_name='Статус заказа'),
        ),
    ]
