# Generated by Django 5.2.7 on 2025-10-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.ManyToManyField(related_name='order_relation', to='book_app.orderdetail', verbose_name='Детали заказа'),
        ),
    ]
