# Generated by Django 5.2.8 on 2025-11-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('Художественная литература', 'Художественная литература'), ('Фантастика', 'Фантастика'), ('Детективы', 'Детективы'), ('Романы', 'Романы')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
