# Generated by Django 5.2.8 on 2025-11-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_book_category_alter_author_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
